### ISSUE TITLE
Kausy not visible on multiple monitors

### ISSUE THREAD

**Issue by otoomet** [soap-the-warrior/invaders#2]
I have a 1080p built-in display, and a (rotated) 1440p display.  This results in a 3360 x 2560 virtual desktop.  The game window fills one screen, and after a while the ufos appear and start shooting.  However, kausy is never visible, and neither are the lives and score text visible.

Note: it works when I switch to a single screen.

**Comment by kaarel-toomet** [comment]
closed by PR #3
